services:

  catalog:
    build:
      context: ./catalog-mock-server
    ports:
      - 3000:3000

  auth:
    build:
      context: ./auth-mock-server
    ports:
      - 3001:3001

  policy:
    build: 
      context: ./policy-mock-server
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:

    # hostname is important; otherwise after each container restart data will be lost
    hostname: 'insurance-rabbitmq'
    build:
      context: ./rabbitmq
    container_name: 'rabbitmq'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 8080:15672
    # volumes:
    #   - ./rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./rabbitmq/log/:/var/log/rabbitmq/
    #   - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
    #   - ./rabbitmq/plugins:/usr/lib/rabbitmq/plugins

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://user:secret@mongo:27017/acme?authSource=admin
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo-network

networks: 
    mongo-network:
      driver: bridge